apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/instance: app-of-apps
  name: app-of-apps
  namespace: argocd
spec:
  destination:
    name: ''
    server: https://kubernetes.default.svc
  project: default
  source:
    path: overlays/dev/argocd-applications
    repoURL: git@github.com:DovDe/k8s-recipe-infra.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
