apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: auth
  labels:
    app: auth
spec:
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image:  "10.0.0.103:5000/auth:latest"
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: auth
            - secretRef:
                name: auth
