apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: mongo
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: "mongo:latest"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "root"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "NotSecure"
          volumeMounts:
            - name: data
              mountPath: /data/db
      volumes:
        - name: data
          persistanceVolumeClaim:
            claimName: mongodb-pvc